### ISSUE TITLE
Use the second GPU in the workstation

### ISSUE THREAD

**Issue by YoungForever222** [barbagroup/cuIBM#37]
Dear Madam/Sir,
  I have a question with my using of cuIBM.
  I have two NVIDIA Tesla K40 in my workstation. The question is how can I configure the cuIBM to use the second one. When I run several examples at the same time, the status always like this:
![20180513104926](https://user-images.githubusercontent.com/18443059/39963349-89bf28f8-569b-11e8-87ae-3945cb528efe.png)
  Could you help me with any options of using the second GPU. 
  Thank you for your patience and looking forward to your reply.
                                                                                                               Yours sincerely
                                                                                                               Hui-Yang Yu

**Comment by piyueh** [comment]
Hi,
You can use the environment variable `CUDA_VISIBLE_DEVICES` to control which GPU you want a specific task to run on.

For example, to launch the first simulation on the GPU with ID 0, in the directory of the 1st simualtion, use
```
$ CUDA_VISIBLE_DEVICES=0 cubim
```
And to use the GPU with ID 1 to run the second simulation, in the directory of the 2nd simualtion, use
```
$ CUDA_VISIBLE_DEVICES=1 cuibm
```

See this webpage for more information about `CUDA_VISIBLE_DEVICES`:
https://devblogs.nvidia.com/cuda-pro-tip-control-gpu-visibility-cuda_visible_devices/

**Comment by YoungForever222** [comment]
Thank you very much! It really works!
